<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class RoomsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('rooms')->insert([
            [
                'hotel_id' => 1,
                'name' => 'Deluxe Room',
                'type' => 'Deluxe',
                'price_per_night' => '500000',
                'facility' => 'AC, TV, Wi-Fi, Breakfast',
                'description' => 'Kamar luas dengan pemandangan kota.',
                'number' => 10,
                //'image' => 'deluxe_room.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 1,
                'name' => 'Superior Room',
                'type' => 'Superior',
                'price_per_night' => '400000',
                'facility' => 'AC, TV, Wi-Fi',
                'description' => 'Kamar nyaman dengan fasilitas lengkap.',
                'number' => 20,
                //'image' => 'superior_room.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 2,
                'name' => 'Executive Suite',
                'type' => 'Suite',
                'price_per_night' => '1000000',
                'facility' => 'AC, TV, Wi-Fi, Breakfast, Living Room',
                'description' => 'Suite mewah dengan ruang tamu terpisah.',
                'number' => 5,
                //'image' => 'executive_suite.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 2,
                'name' => 'Standard Room',
                'type' => 'Standard',
                'price_per_night' => '300000',
                'facility' => 'AC, TV, Wi-Fi',
                'description' => 'Kamar standar dengan fasilitas dasar.',
                'number' => 30,
                //'image' => 'standard_room.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 3,
                'name' => 'Family Room',
                'type' => 'Family',
                'price_per_night' => '750000',
                'facility' => 'AC, TV, Wi-Fi, Breakfast, Extra Bed',
                'description' => 'Kamar keluarga dengan extra bed.',
                'number' => 8,
                //'image' => 'family_room.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 3,
                'name' => 'Single Room',
                'type' => 'Single',
                'price_per_night' => '250000',
                'facility' => 'AC, TV, Wi-Fi',
                'description' => 'Kamar single untuk tamu individu.',
                'number' => 15,
                //'image' => 'single_room.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 4,
                'name' => 'Presidential Suite',
                'type' => 'Suite',
                'price_per_night' => '1500000',
                'facility' => 'AC, TV, Wi-Fi, Breakfast, Living Room, Kitchenette',
                'description' => 'Suite presiden dengan fasilitas mewah.',
                'number' => 2,
                //'image' => 'presidential_suite.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 4,
                'name' => 'Twin Room',
                'type' => 'Twin',
                'price_per_night' => '450000',
                'facility' => 'AC, TV, Wi-Fi, Breakfast',
                'description' => 'Kamar twin dengan dua tempat tidur.',
                'number' => 10,
                //'image' => 'twin_room.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 5,
                'name' => 'Junior Suite',
                'type' => 'Suite',
                'price_per_night' => '850000',
                'facility' => 'AC, TV, Wi-Fi, Breakfast, Living Room',
                'description' => 'Suite junior dengan ruang tamu kecil.',
                'number' => 7,
                //'image' => 'junior_suite.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 5,
                'name' => 'Budget Room',
                'type' => 'Budget',
                'price_per_night' => '200000',
                'facility' => 'AC, TV, Wi-Fi',
                'description' => 'Kamar budget untuk tamu yang hemat.',
                'number' => 25,
                //'image' => 'budget_room.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 6,
                'name' => 'Luxury Suite',
                'type' => 'Suite',
                'price_per_night' => '1200000',
                'facility' => 'AC, TV, Wi-Fi, Breakfast, Living Room, Kitchenette',
                'description' => 'Suite mewah dengan fasilitas premium.',
                'number' => 5,
                //'image' => 'luxury_suite.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 6,
                'name' => 'Comfort Room',
                'type' => 'Comfort',
                'price_per_night' => '600000',
                'facility' => 'AC, TV, Wi-Fi, Breakfast',
                'description' => 'Kamar nyaman dengan pemandangan indah.',
                'number' => 15,
                //'image' => 'comfort_room.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 7,
                'name' => 'Eco Room',
                'type' => 'Eco',
                'price_per_night' => '300000',
                'facility' => 'AC, TV, Wi-Fi',
                'description' => 'Kamar ramah lingkungan dengan fasilitas modern.',
                'number' => 20,
                //'image' => 'eco_room.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 7,
                'name' => 'Business Room',
                'type' => 'Business',
                'price_per_night' => '800000',
                'facility' => 'AC, TV, Wi-Fi, Breakfast, Work Desk',
                'description' => 'Kamar bisnis dengan meja kerja dan fasilitas lengkap.',
                'number' => 10,
                //'image' => 'business_room.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 8,
                'name' => 'Panoramic Suite',
                'type' => 'Suite',
                'price_per_night' => '1500000',
                'facility' => 'AC, TV, Wi-Fi, Breakfast, Living Room, Balcony',
                'description' => 'Suite dengan pemandangan panorama kota.',
                'number' => 4,
                //'image' => 'panoramic_suite.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 8,
                'name' => 'Standard Double',
                'type' => 'Standard',
                'price_per_night' => '400000',
                'facility' => 'AC, TV, Wi-Fi',
                'description' => 'Kamar standar dengan dua tempat tidur.',
                'number' => 30,
                //'image' => 'standard_double.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 9,
                'name' => 'Single Economy',
                'type' => 'Single',
                'price_per_night' => '200000',
                'facility' => 'AC, TV, Wi-Fi',
                'description' => 'Kamar single ekonomis untuk solo traveler.',
                'number' => 25,
                //'image' => 'single_economy.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 9,
                'name' => 'Deluxe King',
                'type' => 'Deluxe',
                'price_per_night' => '700000',
                'facility' => 'AC, TV, Wi-Fi, Breakfast, King Size Bed',
                'description' => 'Kamar deluxe dengan tempat tidur king size.',
                'number' => 12,
                //'image' => 'deluxe_king.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 10,
                'name' => 'Resort Suite',
                'type' => 'Suite',
                'price_per_night' => '2000000',
                'facility' => 'AC, TV, Wi-Fi, Breakfast, Living Room, Private Pool',
                'description' => 'Suite resort dengan kolam renang pribadi.',
                'number' => 3,
                //'image' => 'resort_suite.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hotel_id' => 10,
                'name' => 'Honeymoon Suite',
                'type' => 'Suite',
                'price_per_night' => '1800000',
                'facility' => 'AC, TV, Wi-Fi, Breakfast, Living Room, Jacuzzi',
                'description' => 'Suite untuk bulan madu dengan jacuzzi.',
                'number' => 5,
                //'image' => 'honeymoon_suite.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
